name: lint_python
on: [pull_request, push]
jobs:
  lint_python:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - uses: actions/setup-python@v2
      - run: pip install bandit codespell flake8
      - run: bandit --recursive  --skip B102,B110,B307,B311,B404,B603 .
      - run: codespell --ignore-words-list="crate,nd,te" .
      - run: flake8 . --count --select=E9,F63,F7 --show-source --statistics  # ,F82
